services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql/data
    env_file:
      - .env
    environment:
      MYSQL_DB: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        VUE_APP_API_BASE_URL: ${VUE_APP_API_BASE_URL}
    container_name: quasar_frontend
    restart: unless-stopped
    networks:
      - app-network

  proxy:
    build: ./nginx
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
