"""Initial db setup

Revision ID: 0a06b39aacc6
Revises: 
Create Date: 2025-08-08 08:53:12.963080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a06b39aacc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'applicant_id',
               existing_type=mysql.BIGINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('appointments', 'room_id',
               existing_type=mysql.BIGINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('appointments', 'approver_id',
               existing_type=mysql.BIGINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('role', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('room', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_role', 'user_id',
               existing_type=mysql.BIGINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_role', 'role_id',
               existing_type=mysql.BIGINT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role', 'role_id',
               existing_type=sa.BigInteger(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    op.alter_column('user_role', 'user_id',
               existing_type=sa.BigInteger(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('room', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('role', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('appointments', 'approver_id',
               existing_type=sa.BigInteger(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    op.alter_column('appointments', 'room_id',
               existing_type=sa.BigInteger(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    op.alter_column('appointments', 'applicant_id',
               existing_type=sa.BigInteger(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
